### ISSUE TITLE
Help wanted : Unable to preprocess data .

### ISSUE THREAD

**Issue by Arnavgoyal00** [sangyun884/HR-VITON#1]
I am unable the find the correct scripts to preprocess the data.

**Comment by sangyun884** [comment]
Currently, we do not support preprocessing code for datasets other than those we utilized.
Please refer to the paper for detailed preprocessing procedures.

**Comment by Arnavgoyal00** [comment]
Can you please share the code that you have utilized to preprocess the data if possible?
And also can you please share the paper .

**Comment by koo616** [comment]
We used the pre-trained model of https://github.com/Engineering-Course/CIHP_PGN for human segmentation, and obtained an agnostic image and an agnostic segmentation map by the method in [VITON-HD](https://github.com/shadow2496/VITON-HD)..
For Densepose, please check [detectron2](https://github.com/facebookresearch/detectron2).

Please refer to our paper(https://arxiv.org/pdf/2206.14180.pdf) for more information on the pre-processing :)

**Comment by halcyon370** [comment]
> @Arnavgoyal00 We used the pre-trained model of https://github.com/Engineering-Course/CIHP_PGN for human segmentation, and obtained an agnostic image and an agnostic segmentation map by the method in [VITON-HD](https://github.com/shadow2496/VITON-HD). For Densepose, please check [detectron2](https://github.com/facebookresearch/detectron2).
> 
> Please refer to our paper(https://arxiv.org/pdf/2206.14180.pdf) for more information on the pre-processing :)

Hello, could you simply explain what the data format in 'image-densepose' looks like? Is it range from 0-255 in IUV?

**Comment by MosbehBarhoumi** [comment]
@Arnavgoyal00  If you are still looking for a solution for the pre-processing you can check this issue (it's a tutorial actually):
https://github.com/sangyun884/HR-VITON/issues/45
