### ISSUE TITLE
Article HR-VITON

### ISSUE THREAD

**Issue by julianorinaldi** [sangyun884/HR-VITON#11]
I'm writing an article on my master's degree that use your with reference. 
I need do a little review, but I've dificult with Latex.
Could you share with me you article in Latex please?
My email: julianorinaldi@gmail.com

**Comment by sangyun884** [comment]
Here is the link: https://arxiv.org/e-print/2206.14180

**Comment by julianorinaldi** [comment]
Thanks a lot
