### ISSUE TITLE
Could you supply the code to generate agnostic image?

### ISSUE THREAD

**Issue by dkl78167816** [sangyun884/HR-VITON#13]

**Comment by Atotem** [comment]
Got u bro: https://github.com/bbangsik13/ALIAS

**Comment by dkl78167816** [comment]
> Got u bro: https://github.com/bbangsik13/ALIAS

Thanks!

**Comment by muhammad-ahmed-ghani** [comment]
Hi @Atotem this link is not valid. Can you please share the code once again ? Thanks

**Comment by Atotem** [comment]
Ok, So I contacted the original owner of the repo. According to him, this should do the job:
'https://github.com/shadow2496/VITON-HD/blob/main/datasets.py line 36 for the agnostic representation'

Apparently, This repo is still being developed. I hope I answered your question @muhammad-ahmed-ghani.

**Comment by Atotem** [comment]
Correcting myself, the model in the cp_dataset.py file, generates the agnostic representation.
https://github.com/sangyun884/HR-VITON/blob/54c9b3c59faab90ea7b99b4c839197c1f2128e6b/cp_dataset.py#L49

**Comment by muhammad-ahmed-ghani** [comment]
> Correcting myself, the model in the cp_dataset.py file, generates the agnostic representation.
> 
> https://github.com/sangyun884/HR-VITON/blob/54c9b3c59faab90ea7b99b4c839197c1f2128e6b/cp_dataset.py#L49

Thanks.
