### ISSUE TITLE
Create Train Dataset for our own images!! Help Needed  

### ISSUE THREAD

**Issue by Arnavgoyal00** [sangyun884/HR-VITON#15]
How can generate agnostic-v3.2,densepose and parse-agnostic-v3.2 for my own human image?
Please help!

**Comment by martacosano** [comment]
Hello! the agnostic image and segmentation map are from the VITON-HD repository and the densepose is from detectron2

**Comment by tuyendb** [comment]
> Hello! the agnostic image and segmentation map are from the VITON-HD repository and the densepose is from detectron2

what about openpose ????

**Comment by koo616** [comment]
Hello guys. I just created 'Preprocess.md', the description for our preprocess including human parsing.
Please check it :)
