### ISSUE TITLE
Understanding the TPS / Warp Operations

### ISSUE THREAD

**Issue by torphix** [sangyun884/HR-VITON#16]
Hi! 
Thanks for sharing your work it helps develop my understanding.

I am trying to understand the TPS warp operations am I correct in saying:

- The model predicts the TPS transformation parameters 
- The TPS transformation parameters are then applied to each level of the latent features (ie the downscaled image features)?
- The TPS transformation parameters are learned by back propagating between the ground truth warped segmentation map (only the cloth item) and the predicted warped cloth mask?

Thank you kindly

**Comment by Atotem** [comment]
Got u bro: https://khanhha.github.io/

**Comment by torphix** [comment]
@Atotem ❤️
