### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by nagexiaochengzi** [sangyun884/HR-VITON#25]
Hello, where is the code for some modules such as image segmentation, body posture, etc. in the project?

**Comment by koo616** [comment]
Hello @nagexiaochengzi .
The code I used for the preprocess is described in 'Preprocess.md'. Please check it :)

**Comment by tuyendb** [comment]
> Hello @nagexiaochengzi . The code I used for the preprocess is described in 'Preprocess.md'. Please check it :)

How can u create image-parse-agnostic-v3.2

**Comment by koo616** [comment]
@tuyendb 
Please check 'get_parse_agnostic.py' python code I uploaded yesterday.

**Comment by tuyendb** [comment]
> @tuyendb Please check 'get_parse_agnostic.py' python code I uploaded yesterday.

I have a question. Can I replace openpose keypoints detection by other methods, such as mediapipe,...

**Comment by tuyendb** [comment]
> @tuyendb Please check 'get_parse_agnostic.py' python code I uploaded yesterday.
Can I inference a image with size that is different from your size (768,1024)? I tried and failed. If i can do this, do I have to modify input size of the network
