### ISSUE TITLE
Specifications for Generation of 'image-parse-agnostic-v3.2'

### ISSUE THREAD

**Issue by Atotem** [sangyun884/HR-VITON#29]
Hi, following your code, in order to generate the train/test dataset I apparently must prepare the 'image-parse-agnostic-v3.2'. It looks like it's the same file as in the 'openpose_img', but the regions of the neck and torso are dropped to zero values, but, with some peculiar differences. Which is the process to generate this type of data? Why isn't being performed online. Greetings.

Sincerely,
@Atotem

**Comment by Atotem** [comment]
You know what? I'm training so it is not urgent. I made a shortcut but It would be cool to have that original source code.

**Comment by koo616** [comment]
Hello @Atotem .
Now you can get parse-agnostic images using 'get_parse_agnostic.py' code I uploaded. Please check it :)
