### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by psx2** [sangyun884/HR-VITON#3]
Getting the following error when running on Windows.

```
Traceback (most recent call last):
  File "test_generator.py", line 249, in <module>
    main()
  File "test_generator.py", line 225, in main
    board = SummaryWriter(log_dir=os.path.join(opt.tensorboard_dir, opt.tocg_checkpoint.split('/')[-2], opt.tocg_checkpoint.split('/')[-1], opt.datamode, opt.datasetting))
IndexError: list index out of range
```

Any idea?

**Comment by verc3l** [comment]
I am running on a completely fresh AWS Linux instant.

Upon testing the command `python3 test_generator.py`, I am greeted with `FileNotFoundError: [Errno 2] No such file or directory: './data/zalando-hd-resize/./data/zalando-hd-resize/test_pairs.txt'`.

**Comment by Arnavgoyal00** [comment]
@psx2 @verc3l  I need help to preprocess the input data, particularly in human segmentation .

**Comment by sangyun884** [comment]
@verc3l  Did you follow the test command we instructed?

**Comment by koo616** [comment]
@verc3l We fixed it. Please check the updated readme try it again.
