### ISSUE TITLE
How to test HR-Viton on 2 images.

### ISSUE THREAD

**Issue by ahmadmustafaanis** [sangyun884/HR-VITON#30]
Hi, I do have 2 images, 1 is shirt, 2nd is person. How can I test on these 2 images. I am unable to do so.

**Comment by koo616** [comment]
Hello @ahmadmustafaanis .
For your custom dataset, you should preprocess them yourself.
'Preprocess.md' will be helpful. Please check it :)

**Comment by shivansh-chanana** [comment]
Hey any idea how much time does preprocessing custom images take? Any approximate idea depending on low end and high end gpu. thankyou :)
