### ISSUE TITLE
draw openpose

### ISSUE THREAD

**Issue by tiamo405** [sangyun884/HR-VITON#31]
I have coordinates of body points and want to join them. However my ouput is not what I expected. The difference is the color of the body segments and the width. how should i edit it now or can anyone give me the code for reference? BODY_25
wish : https://drive.google.com/file/d/106ST7yUzzboQ9r-KcMulm6AkcwHpP2MN/view?usp=sharing
actual: https://drive.google.com/file/d/1YU34RU1C-zOIbrv0QwNdZSYcvEBtRD0V/view?usp=sharing

**Comment by koo616** [comment]
Hello @tiamo405 .
You can check 'Preprocess.md' for the detailed process of the openpose data. Please check it :)
