### ISSUE TITLE
How to test with news persons and clothes?

### ISSUE THREAD

**Issue by julianorinaldi** [sangyun884/HR-VITON#32]
In directory test/cloth I put a new clothes file, 1024x768
In directory test/image I put a new woman person file, 1024x768
I changed the file test_pairs.txt with only my test.

But when I ran, the error showed is: FileNotFoundError: [Errno 2] No such file or directory: 'HR-VITON/data/zalando-hd-resized/test/cloth-mask/00000_00.jpg'

It's because I dont generated the cloth-mask.

What I need run to generate the artifact to I run?

**Comment by julianorinaldi** [comment]
my dataset override test: https://drive.google.com/uc?id=1h6JTGXopAJxU5zBBTuh58Uw-JPmPW3sm&authuser=0&export=download

**Comment by Deepak2405** [comment]
Did you get any answer for this?

**Comment by julianorinaldi** [comment]
No yet

**Comment by lujinglmy** [comment]
> my dataset override test: https://drive.google.com/uc?id=1h6JTGXopAJxU5zBBTuh58Uw-JPmPW3sm&authuser=0&export=download



> In directory test/cloth I put a new clothes file, 1024x768 In directory test/image I put a new woman person file, 1024x768 I changed the file test_pairs.txt with only my test.
> 
> But when I ran, the error showed is: FileNotFoundError: [Errno 2] No such file or directory: 'HR-VITON/data/zalando-hd-resized/test/cloth-mask/00000_00.jpg'
> 
> It's because I dont generated the cloth-mask.
> 
> What I need run to generate the artifact to I run?

You have to make that yourself

**Comment by lujinglmy** [comment]
> > my dataset override test: https://drive.google.com/uc?id=1h6JTGXopAJxU5zBBTuh58Uw-JPmPW3sm&authuser=0&export=download
> 
> > In directory test/cloth I put a new clothes file, 1024x768 In directory test/image I put a new woman person file, 1024x768 I changed the file test_pairs.txt with only my test.
> > But when I ran, the error showed is: FileNotFoundError: [Errno 2] No such file or directory: 'HR-VITON/data/zalando-hd-resized/test/cloth-mask/00000_00.jpg'
> > It's because I dont generated the cloth-mask.
> > What I need run to generate the artifact to I run?
> 
> You have to make that yourself

So once you've done this and you have to do something else yourself, this is the data preprocessing
