### ISSUE TITLE
Help me with transform new images to process in network HR VITON

### ISSUE THREAD

**Issue by julianorinaldi** [sangyun884/HR-VITON#33]
I'm writing an article with references HR Viton and I need put new photos to dataset HD-Viton, but I didn't found the code that transforme a pair (woman weared + clothes) to others images to process in Network model. I need help, without this my article in master degree will be disaster.

![HD-Viton-Dataset](https://user-images.githubusercontent.com/2027551/198856794-5af290f1-0078-41c5-87fe-4440aeea918d.png)

With image 1 and 3, I need to trasnform to 2,4,5,6,7 and code 8. Can you help me? 
My email is julianorinaldi@gmail.com or my univertisy mail: julianorinaldi@alunos.utfpr.edu.br.

**Comment by koo616** [comment]
Hello @julianorinaldi .
Sorry for the late reply. I just uploaded 'Preprocess.md', the description for my preprocess in detail.
Please check it :)
And I really hope that your degree will be fine.
