### ISSUE TITLE
Offset Generated During Training

### ISSUE THREAD

**Issue by Atotem** [sangyun884/HR-VITON#34]
Hi, I'm training with my own dataset and had some initial results with 1000 epochs. However, I noticed that the targeted garment moves from its position during training. Do you know what this can be happening? I followed the same preprocessing process but can't figure out at this point what can be causing it. Greetings!

![00364_00018](https://user-images.githubusercontent.com/62360050/200513553-c007c8ae-1ccd-4984-85d7-b639809bba0f.png)

Sincerely,
@Atotem

**Comment by Atotem** [comment]
Hi @koo616 , Are your sure you used torchgeometry.image.GaussianBlur()? and not torchvision.transforms.GaussianBlur()? Because for torchgeometry I have to transform the image to tensor. Also, I get images but with a lot of unwanted data in the edges. I tried ```ImageFilter.ModeFilter(size=3)``` from Pillow but I'm still trying to figure out the kernel size. Any ideas?

**Comment by khurramkhalil** [comment]
Hi @koo616,
I am facing similar issues. I have used` ImageFilter.ModeFilter(size=10)`. Can you share your image agnostic and pose generation code so that we both can reconcile? Thanks
