### ISSUE TITLE
Data Preprocessing!

### ISSUE THREAD

**Issue by netuserjun** [sangyun884/HR-VITON#35]
To be honest, it is the most roughly explained storage I've ever seen.
The preprocessing process is so unexplained that it is impossible to reproduce.
I even tried two days to get the agnostic and parse with the images of the dataset you provided, 
but my results are different from yours.
Can't you be a little kinder?
![02567_01](https://user-images.githubusercontent.com/38284141/201866748-a415da67-0a59-4995-b5cf-2fccc5ec5386.png)
![02567_03](https://user-images.githubusercontent.com/38284141/201866766-b83da28c-99a3-4c7d-8fca-006fc941695c.png)
![02567_00_01111_00](https://user-images.githubusercontent.com/38284141/201866848-9c1b4acc-5ca7-4fbf-b199-c5a55db3e0f0.png)
![02567_00_01111_01](https://user-images.githubusercontent.com/38284141/201866869-d6d6f046-0985-4707-98f2-e669a1f68dde.png)

**Comment by koo616** [comment]
Hello @netuserjun.
I just uploaded 'Preprocess.md' and 'get_parse_agnostic.py'. Please check them.
