### ISSUE TITLE
I want to ask how your densepose is generated

### ISSUE THREAD

**Issue by wang674** [sangyun884/HR-VITON#36]
Hello, I want to ask how your densepose is generated. I  generated a character image after it。Can you help me?
![image](https://user-images.githubusercontent.com/81903513/202857315-1d19fe50-5aa2-4ec3-a1d4-10c1498c9516.png)

**Comment by tuyendb** [comment]
> Hello, I want to ask how your densepose is generated. I generated a character image after it。Can you help me? ![image](https://user-images.githubusercontent.com/81903513/202857315-1d19fe50-5aa2-4ec3-a1d4-10c1498c9516.png)

set alpha = 1 and change tile_img into black_background
