### ISSUE TITLE
Are training pairs meant to be mismatched?

### ISSUE THREAD

**Issue by nihirv** [sangyun884/HR-VITON#4]
Hi,

I downloaded the dataset provided in the VITON-HD repo.

Both papers train on the piece of clothing that is already on the model.

However the provided train_pairs.txt contains mismatched human and clothing ids.

Am I misunderstanding something or should I re-create the train_pairs file?

**Comment by koo616** [comment]
@nihirv 
As you can see from our code, the mismatch of train_pairs.txt has no effect on training :)

**Comment by nihirv** [comment]
@koo616 I'm not sure this is true. I ran a version with mismatched pairs and one with aligned pairs. The mismatched pairs can create a correct geometry on the visualisation, but fails to capture anything useful about the colours or patterns on the clothing. The results with the aligned pairs are significantly better

**Comment by nihirv** [comment]
> @nihirv: As you, I have retrained with paired and unpaired data, respectively. Only paired data can create a convincing result and maybe there has been a mistake in Line 43-44 in cp_dataset.py.

Yeah actually - if `c_names` and `im_names` were swapped from paired and unpaired respectively. I.e.:

```python
self.c_names['paired'] = im_names
self.c_names['unpaired'] = c_names
```

Then the code would execute with the correct data I believe

**Comment by nihirv** [comment]
@HITRainer Did you train on the original data they provided? What are your results looking like? My current results (am currently about 60k steps through training) are not as high quality as the paper samples. I'm unsure how cherry picked the samples in the paper were, and would like to know if these poor results are because of the additional data I added in to train with or if this is the model's standard behaviour

**Comment by HITRainer** [comment]
@nihirv  I'm not sure the reason, but I trained the model with 100K iters with train_pairs_zalando.txt they provided and can not recurrent authors results. Still troubleshooting bugs.

**Comment by sangyun884** [comment]
> @HITRainer Did you train on the original data they provided? What are your results looking like? My current results (am currently about 60k steps through training) are not as high quality as the paper samples. I'm unsure how cherry picked the samples in the paper were, and would like to know if these poor results are because of the additional data I added in to train with or if this is the model's standard behaviour

Sorry, we made a mistake while cleaning our code! We corrected our code so please check :)

**Comment by sangyun884** [comment]
We found that there was a mismatch between train_pairs.txt we used and the one in the VITON-HD repo. We updated our code so please check now.

**Comment by nihirv** [comment]
@sangyun884 Thanks for the changes. I had already modified the code to be similar to what you changed - hopefully the changes help future users.

When I run it on the provided dataset it seems to be fitting well. Though when adding other data to the dataset the results aren't as promising. Seems like an issue for me to figure out though.

Could you keep this issue open for another day or 2 until I finish training?

Thank you again!

**Comment by HITRainer** [comment]
@nihirv Have you ever encountered that the program will get stuck when training the train_generator.py with multiple GPUs. In more detail, it will be stuck when calling `loss_gen_scaled.backward()` in Line 317

**Comment by nihirv** [comment]
Sorry for the late reply @HITRainer. I'm only training on one GPU. Are you still facing the issue?

**Comment by HITRainer** [comment]
@nihirv Hi, thanks for replying. I have solved that problem already.

**Comment by nihirv** [comment]
I'll close this issue then:)

**Comment by nkise-nlab** [comment]
> @nihirv Hi, thanks for replying. I have solved that problem already.

Hi @nihirv , could you please share the details how have you solved this issue?

**Comment by kinivi** [comment]
> @nihirv Hi, thanks for replying. I have solved that problem already.

Hi @nihirv , could you please share the details of how have you solved this issue?

**Comment by nihirv** [comment]
> > @nihirv Hi, thanks for replying. I have solved that problem already.
> 
> Hi @nihirv , could you please share the details of how have you solved this issue?

@kinivi I think you meant to tag @HITRainer

**Comment by kinivi** [comment]
> > @nihirv Hi, thanks for replying. I have solved that problem already.
> 
> Hi @nihirv , could you please share the details of how have you solved this issue?

Ooops, indeed :). @HITRainer could you please help?

**Comment by HITRainer** [comment]
hi @kinivi 
A bit of a cumbersome approach, change its DP to DDP, which indeed works.
