### ISSUE TITLE
Use my own cloth fail, but add your testdataset mask can

### ISSUE THREAD

**Issue by dkhonker** [sangyun884/HR-VITON#44]
Hello,
I use  my own clothes  image to test but i get a bad result.
![img](https://i.ibb.co/JQXxw9G/leaves-1.jpg)
![img](https://i.ibb.co/ZBd1H3D/20221230183400.png)

But I randomly chose a mask from your test set instead of my own cloth mask.
I get a good result.

![img](https://i.ibb.co/Xs15R26/20221230174746.png)

Do you know what the problem is？

**Comment by maiskovich** [comment]
@dkhonker what was the issue?

**Comment by dkhonker** [comment]
I found that the background of the data set was not (255,225,255), which affected the quality of the algorithm.
The correct RGB of the background is (246,246,246).
