### ISSUE TITLE
About test own data question

### ISSUE THREAD

**Issue by kelisiya** [sangyun884/HR-VITON#6]
Nice work ! Now I want to try my cloth data to test your  work , but how to get clothing agnostic? I found CIHP_PGN emantic part segmentation and  detectron2 for densepose . But HR-VITION  dont have clothing agnostic code . Can you help me ?

**Comment by usmannamjad** [comment]
@kelisiya I have been trying to reproduce the results of https://github.com/shadow2496/VITON-HD for images of other people. Can you briefly tell me the steps for applying this technique on images other than the test data.

**Comment by koo616** [comment]
@kelisiya I just committed the code for a parse agnostic image. Please check the code :)
And our dataset code contains the process for a clothing-agnostic human image.
