### ISSUE TITLE
image-parse-agnostic-v3.2

### ISSUE THREAD

**Issue by MosbehBarhoumi** [sangyun884/HR-VITON#68]
One of the authors stated that they utilized the get_parse_agnostic.py function from the GitHub repository https://github.com/sangyun884/HR-VITON/blob/main/get_parse_agnostic.py to obtain image-parse-agnostic-v3.2. However, I observed that the resulting data differed from the pre-processed data.

**Comment by Blurjp** [comment]
How did you figure this out?

**Comment by SalehAhmad1** [comment]
What's the update on this issue? When we use HR-VTON's function to generate the "image-parse-agnostic-v3.2.", our data is grayscaled and not RGB like as in the zelando's preprocessed data
