### ISSUE TITLE
About training settings

### ISSUE THREAD

**Issue by HITRainer** [sangyun884/HR-VITON#7]
Hi, thanks for sharing your codes.
But I was confused by the difference between your codes and the description in your paper during retraining your model.
For example, when training try-on generator, the code will train the model for 300K iters but it is only 100k mentioned in your paper (Sec 4.1, last line in Page8).
So, are the excellent results in your paper trained according to the settings mentioned in the paper or according to the released code settings. And which one should us follow to get your paper results.

**Comment by jweihe** [comment]
@HITRainer   Can you successfully run the test file of this code? I have some problems

**Comment by sangyun884** [comment]
Follow the description in the paper and feel free to early stop the training whenever needed.
