### ISSUE TITLE
dense pose

### ISSUE THREAD

**Issue by sankalp2K** [sangyun884/HR-VITON#8]
which dense pose model is used?

**Comment by koo616** [comment]
@sankalp2K 
We use "densepose_rcnn_R_50_FPN_s1x" model in the [detectron2](https://github.com/facebookresearch/detectron2) repository :)

**Comment by sankalp2K** [comment]
Thank You, but how to get segmentation visualization from a dense pose without having the segmentation map blended on top of the original image?

**Comment by Gzzgz** [comment]
alpha=1

**Comment by RAJA-PARIKSHAT** [comment]
@Gzzgz what do you mean by alpha=1? I am able to run and get the segmentation map but it is blended with the original image

**Comment by Arnavgoyal00** [comment]
How are you able to use detectron to get the densepose image , as in the training dataset?

**Comment by RAJA-PARIKSHAT** [comment]
@Arnavgoyal00 go to detectron2 repo, clone it and follow the link  https://github.com/facebookresearch/detectron2/blob/main/projects/DensePose/doc/GETTING_STARTED.md there will be installation instruction.

Once you have installed you can use https://github.com/facebookresearch/detectron2/blob/main/projects/DensePose/doc/TOOL_APPLY_NET.md#:~:text=python%20apply_net.py%20show%20configs/densepose_rcnn_R_50_FPN_s1x.yaml%20%5C%0Ahttps%3A//dl.fbaipublicfiles.com/densepose/densepose_rcnn_R_50_FPN_s1x/165712039/model_final_162be9.pkl%20%5C%0Aimage.jpg%20bbox%2Cdp_segm%20%2Dv without bbox argument to generate densepose image. But the problem will be it will be blending original image.

For that you will have to change some parameters in visualization. goto Densepose->densepose->vis->densepose_results.py and in class **DensePoseResultsFineSegmentationVisualizer** set alpha =1

**Comment by vikashranjan** [comment]
@RAJA-PARIKSHAT I tried setting alpha = 1, but the output is still blended with the original Image.

**Comment by koo616** [comment]
Unfortunately, even I have difficulty reproducing densepose images exactly on the dataset.
I am currently working on a new dataset using the densepose image obtained by DumpAction in 'apply_net.py'.
It seems that there is no significant problem with performance of HR-VITON :)
