### ISSUE TITLE
Full body outfit

### ISSUE THREAD

**Issue by armangrigoryan96** [sangyun884/HR-VITON#9]
Hi, thank you for the great work. 
Just want to ask is it possible to train the model only with the custom full-body outfit? Or is it designed only for images where a person is not completely visible?

**Comment by Jayyyyyyyyyyyy** [comment]
look at the training dataset and the demo results, the trained model that auther provided supports up-body in a pic only. I tried full-body, the result is not very effective yet.

**Comment by armangrigoryan96** [comment]
@Jayyyyyyyyyyyy thank you for your observation. I meant training on my custom dataset with a full body outfit, not using the pretrained model. So is it possible to get as convincing results as for the demo if I train myself on the custom images?

**Comment by martacosano** [comment]
Hello @armangrigoryan96 ! Did you train with your own full body images? Did you achieve good results? Thank you!

**Comment by armangrigoryan96** [comment]
> Hello @armangrigoryan96 ! Did you train with your own full body images? Did you achieve good results? Thank you!

Hey, yes I did. It worked out quite well.

**Comment by armangrigoryan96** [comment]
> Hello @armangrigoryan96 ! Did you train with your own full body images? Did you achieve good results? Thank you!

Kindly ask you to email me at armg187@gmail.com for more details. Sorry, I am not checking the messages on the GitHub page very often, better email me.

**Comment by koo616** [comment]
I think I can't confirm the performance because I haven't trained it with a dataset including the full body. The recently released DressCode dataset contains the full body, so I think you can use it to train the model and check its performance :)
